format = "$shell$hostname$username$time$directory$jobs$all$git_branch$git_status$status$cmd_duration$battery$character"
right_format = "${custom.git_metrics_main_added_deleted}$git_commit$conda$kubernetes"
add_newline = false

[line_break]
# Prompt is one line, not two lines
disabled = true

[hostname]
disabled = false
ssh_only = false
ssh_symbol = 'SSH '
style = 'bold red'
format = "[$hostname $ssh_symbol]($style)"

[username]
disabled = false
format = "[$user]($style) @ "

[shell]
fish_indicator = ""
unknown_indicator = "sh? "
bash_indicator = "bash "
zsh_indicator = "zsh "
powershell_indicator = "psh "
# How to erase if it's only a space?
# format = '[($indicator )]($style)'
# format = '([$indicator]($style) )'
format = '[$indicator]($style)'
style = "white"
disabled = false

[custom.git_metrics_main_added_deleted]
when = "test -d .git"
shell = "dash"
# Sample outputs:
# 1 file changed, 2 insertions(+), 2 deletions(-)
# 1 file changed, 2 deletions(-)
# 1 file changed, 2 insertions(+)
command = "git diff main --shortstat | sed 's/.*file.* changed, // ; s/\\([0-9]*\\) insertion/\\1/ ; s/\\([0-9]*\\) deletion/\\1/ ; s/s\\|(\\|)\\|,//g'"
format = " [$symbol($output)]($style)"
style = "bold underline fg:blue"

[directory]
style = "bright-white bold"
truncation_length = 3
truncation_symbol = ""
[directory.substitutions]
"powerflex_edge_" = ""
"powerflex_cloud_" = ""
"powerflex_" = ""
"central_system" = "CS"
"traffic_manager" = "traffman"
"storage_interface" = "storint"
"storage_simulator" = "storsim"
"edge_device_manager" = "devman"
"presentations" = "pr"
"2022_CognizantFullstackNanodegree_SessionLead" = "2022nd"

[time]
disabled = false
style = "dimmed white"
format = "[$time]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold fg:bright-yellow"
symbol = ""
truncation_length=14

[git_state]
disabled = true

[git_metrics]
disabled = true
added_style = "bold underline fg:bright-green"
deleted_style = "bold underline fg:blue"

[git_status]
style = "bright-yellow"
format = "([$all_status$ahead_behind]($style) )"
stashed = "S"

[status]
# Show exit code of last command
disabled = false
format = '[\[$status $common meaning\]]($style) '

[[battery.display]]
threshold = 25

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[X](bold red)"

[cmd_duration]
min_time = 60_000
show_milliseconds = false
format = "[$duration]($style) "

[kubernetes]
disabled = false
format = ' [$symbol$context( \($namespace\))]($style)'
style = "fg:#88ddff"
[kubernetes.context_aliases]
"0007-04-hugoroguh" = "0007-04"
"1337-77-hugo" = "1337-77"
"gke_edf-re-powerflex-dev-16b1_us-west2_gke-dev-powerflex-cluster" = "gke-dev"
"powerflex-0001-25-powerflex-leghorn" = "foghorn-leghorn-hq"

[git_commit]
commit_hash_length = 4
only_detached = false
tag_disabled = false
format = " [$hash$tag]($style)"
style = "fg:bright-yellow"

[conda]
ignore_base = false
format = " [$symbol $environment]($style)"
symbol = "ìÜò"
disabled = false

[gcloud]
disabled = true

[package]
format = "[$symbol$version]($style) "
symbol = ""

########## REMOVE "via"
[python]
disabled = true
# Keep up to date with latest default, but omit "via"
style = "white"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
style = "white"
format = "[$symbol($version )]($style)"

[nodejs]
disabled = true
style = "white"
format = "[$symbol($version )]($style)"

[ocaml]
# This is a double humped camel!!!!!!!! üê´
style = "white"
format = "[$symbol($version )]($style)"

[perl]
# This is a single humped camel!!!!!!!! üê™
style = "white"
format = "[$symbol($version )]($style)"
